

### obteniendo datos de un usuario aleatorio
GET https://randomuser.me/api


### obteniendo datos de un usuario aleatorio
GET https://randomuser.me/api/?nat=gb

### obteniendo todas las publicaciones
GET https://jsonplaceholder.typicode.com/posts

### obteniendo una sola publicación

GET https://jsonplaceholder.typicode.com/posts/2

### eliminando una publicación
DELETE https://jsonplaceholder.typicode.com/posts/1

### Actualizando una publicación por Id

PUT https://jsonplaceholder.typicode.com/posts/1
content-type: application/json

{
    "title":"publicación nro 1000",
    "body":"procesado"
}

### creando una nueva publicación

POST https://jsonplaceholder.typicode.com/posts 
content-type: application/json

{
    "title":"aprendiendo vscode",
    "body":"bien"
}
